#spring.application.name=crud-java-backend

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_java"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true